name: Deploy backend Azure

env:
  AZURE_WEBAPP_NAME: DEV-BASIC-CI-CD
  
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.1

    - name: Run tests
      run: |
        cd backend
        go test -v ./...
  

    