name: Deploy backend Azure

env:
  AZURE_WEBAPP_NAME: basic-ci-cd-backend
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend-azure.yml'

permissions:
  id-token: write
  contents: read
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.1

    - name: Run tests
      run: |
        cd backend
        go test -v ./...
  docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/basic-ci-cd-backend:latest
    
  deploy-azure:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Azure CLI script
        run: |
          az containerapp up \
          --name basic-ci-cd-backend \
          --resource-group basic-ci-cd \
          --location centralus \
          --environment 'basic-ci-cd' \
          --image vacaramin/basic-ci-cd-backend:latest \
          --target-port 80 \
          --ingress external \
          --query properties.configuation.ingress.fqdn 

    