name: Frontend deploy 
on: 
  push:
      branches:
        - main
      paths:
        - 'frontend/**'
        - '.github/workflows/dev-frontend-deploy.yml'
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      