
name: Deploy to Firebase Hosting DEV Frontend
on: 
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/firebase-hosting-deploy.yml'

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV_BASIC_CI }}'
          channelId: live
          projectId: dev-basic-ci
